### PR TITLE
Add Order By Score (ASC and DESC)

### PR DESCRIPTION
**Pull request by webimpacto-vtex-apps**
#### What is the purpose of this pull request?

Use the product Search order by Score DESC and ASC. 
Updated name of message files to the new format (en.json required)

#### What problem is this solving?

Clients want order the Search Results by default with the product Score field.

#### How should this be manually tested?

1. In StoreFront go to Search Results Page.
2. Change the "Order By Selector"  to ordenation.score.ascending or ordenation.score.descending
3. Check the results are the same that the Search API:  https://{{acccount}}.vtexcommercestable.com.br/api/catalog_system/pub/products/search/{department}/{category}/?map=c,c&O=OrderByScoreDESC

#### Types of changes

* [ ] Bug fix (a non-breaking change which fixes an issue)
* [x] New feature (a non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Requires change to documentation, which has been updated accordingly.

### CODE REVIEW

**Comment by luciannojunior** [comment]
Could you add a link to a workspace with this changes? And also, is there any related PR's?

**Comment by webimpacto-vtex-apps** [comment]
Worskpace: pmartin
Account: naturitasfr 
https://pmartin--naturitasfr.myvtex.com/

And nop, there isn't another related PR.

**Comment by luciannojunior** [comment]
@webimpacto-vtex-apps I will merge it right now. Do you think is it appropriate to replicate this feature on our master branch?

**Comment by pablomartin89** [comment]
> @webimpacto-vtex-apps I will merge it right now. Do you think is it appropriate to replicate this feature on our master branch?

Hi @luciannojunior , yes it's appropriate, it's a new feature documented on this page: https://help.vtex.com/tutorial/how-does-the-score-field-work--1BUZC0mBYEEIUgeQYAKcae 
If we replicate this feature on Master, clients with Store V2 will can use it.  

Only it's needed apply the change on file: react/utils/search.js , cause the 'rename of message files' it's already done on master. 

Regards.

**Pull request merged**
