### PR TITLE
Remove unnecessary function

### PR DESCRIPTION
**Pull request by thalytafabrine**
#### What problem is this solving?
now, `searchMetadata` will come with the default encoded value for slash, so we no longer need this function.

#### How to test it?

[Workspace](https://encodeurl--biscoind.myvtex.com/3-48m%2fs?_q=3-48m/s&map=ft)

#### Screenshots or example usage:

image

#### Related to / Depends on

Depends on https://github.com/vtex/rewriter/pull/186

### CODE REVIEW

**Review by hiagolcm — COMMENTED** [review]
Can we remove this file as well?
`react/utils/decodeForwardSlash.ts`

**Comment by thalytafabrine** [comment]
> Can we remove this file as well?
> `react/utils/decodeForwardSlash.ts`
> 
> What about this [line](https://github.com/vtex-apps/store/blob/3dd71f5cb6bf4b490d985f1718fb1425d58f4e5a/react/SearchContext.jsx#L86)?
> Will we need to keep it?

@hiagolcm  I already removed this file :)
Yes, we need to keep because this is necessary to translate the value that comes from the rewriter: https://github.com/vtex/rewriter/pull/186

**Comment by hiagolcm** [comment]
> > Can we remove this file as well?
> > `react/utils/decodeForwardSlash.ts`
> > What about this [line](https://github.com/vtex-apps/store/blob/3dd71f5cb6bf4b490d985f1718fb1425d58f4e5a/react/SearchContext.jsx#L86)?
> > Will we need to keep it?
> 
> @hiagolcm I already removed this file :)
> Yes, we need to keep because this is necessary to translate the value that comes from the rewriter: [vtex/rewriter#186](https://github.com/vtex/rewriter/pull/186)

The idea was to remove this `$` encode completely 🤔 . But if it is not possible, couldn't we keep this replace in the rewriter? This way we can keep this logic in a single place
You could do this replace after that [`for` loop](

The idea was to remove this `$` encode completely 🤔 . But if it is not possible, couldn't we keep this replace in the rewriter? This way we can keep this logic in a single place.
You could do this replace after that [`for` loop](https://github.com/vtex/rewriter/blob/a7f288cc47c3921e03f44c8eb75de66e95829f8a/node/utils/paths.ts#L24))

**Comment by thalytafabrine** [comment]
> > @hiagolcm I already removed this file :)
> 
> OMG, sorry. I didn't see that 👓 🤦
> 
> > Yes, we need to keep because this is necessary to translate the value that comes from the rewriter: [vtex/rewriter#186](https://github.com/vtex/rewriter/pull/186)
> 
> Couldn't we keep this replace in the rewriter? This way we can keep this logic in a single place.
> You could do this replace right after that [`for` loop](https://github.com/vtex/rewriter/blob/a7f288cc47c3921e03f44c8eb75de66e95829f8a/node/utils/paths.ts#L24)
> 
> First, `replace("%2f", "$2f")`
> Then the for loop
> and finally `replace("$2f", "%2f")`.
> 
> This way the client-side doesn't need to know this rule
> 
> In addition, have you tested other tricky characters like `?` or `&`?

this wouldn't work cause there is an `encodeURI` right after calling this function, but I did this replace after the encode and it worked. tkss!

**Review by hiagolcm — APPROVED** [review]

**Pull request merged**
